version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ~/plex-media/:/user-media
      - /mnt/media0001/plex-media:/external
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 32400 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
